config/routes.rb
Rails.application.routes.draw do
  resources :payrolls
  resources :authorizations
  resources :requests
  resources :research_groups
  resources :contracts
  resources :user_experiences
  resources :patents
  resources :profiles
  resources :degrees
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :degree_types
  resources :vacants
  resources :research_types
  resources :fees
  resources :researcher_categories
  resources :experiences
  resources :contracted_teaching_categories
  resources :aspiring_teaching_categories
  resources :patent_types
  resources :areas
  resources :resources
  resources :actions
  resources :permissions
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "main#home"
end

app/models/researcher_category.rb
# == Schema Information
#
# Table name: researcher_categories
#
#  id          :integer          not null, primary key
#  descripcion :string
#  puntaje     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class ResearcherCategory < ApplicationRecord
    has_many :users
end

app/controllers/researcher_categories_controller.rb
class ResearcherCategoriesController < ApplicationController
  before_action :set_researcher_category, only: %i[ show edit update destroy ]

  # GET /researcher_categories or /researcher_categories.json
  def index
    @researcher_categories = ResearcherCategory.all
  end

  # GET /researcher_categories/1 or /researcher_categories/1.json
  def show
  end

  # GET /researcher_categories/new
  def new
    @researcher_category = ResearcherCategory.new
  end

  # GET /researcher_categories/1/edit
  def edit
  end

  # POST /researcher_categories or /researcher_categories.json
  def create
    @researcher_category = ResearcherCategory.new(researcher_category_params)

    respond_to do |format|
      if @researcher_category.save
        format.html { redirect_to researcher_category_url(@researcher_category), notice: "Researcher category was successfully created." }
        format.json { render :show, status: :created, location: @researcher_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @researcher_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /researcher_categories/1 or /researcher_categories/1.json
  def update
    respond_to do |format|
      if @researcher_category.update(researcher_category_params)
        format.html { redirect_to researcher_category_url(@researcher_category), notice: "Researcher category was successfully updated." }
        format.json { render :show, status: :ok, location: @researcher_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @researcher_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /researcher_categories/1 or /researcher_categories/1.json
  def destroy
    @researcher_category.destroy

    respond_to do |format|
      format.html { redirect_to researcher_categories_url, notice: "Researcher category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_researcher_category
      @researcher_category = ResearcherCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def researcher_category_params
      params.require(:researcher_category).permit(:descripcion, :puntaje)
    end
end

app/helpers/researcher_categories_helper.rb
module ResearcherCategoriesHelper
end

app/views/researcher_categories/_form.html.erb
<%= form_with(model: researcher_category) do |form| %>
  <% if researcher_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(researcher_category.errors.count, "error") %> prohibited this researcher_category from being saved:</h2>

      <ul>
        <% researcher_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :puntaje, style: "display: block" %>
    <%= form.number_field :puntaje %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/researcher_categories/_researcher_category.html.erb
<div id="<%= dom_id researcher_category %>">
  <p>
    <strong>Descripcion:</strong>
    <%= researcher_category.descripcion %>
  </p>

  <p>
    <strong>Puntaje:</strong>
    <%= researcher_category.puntaje %>
  </p>

</div>

app/views/researcher_categories/edit.html.erb
<h1>Editing researcher category</h1>

<%= render "form", researcher_category: @researcher_category %>

<br>

<div>
  <%= link_to "Show this researcher category", @researcher_category %> |
  <%= link_to "Back to researcher categories", researcher_categories_path %>
</div>

app/views/researcher_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Researcher categories</h1>

<div id="researcher_categories">
  <% @researcher_categories.each do |researcher_category| %>
    <%= render researcher_category %>
    <p>
      <%= link_to "Show this researcher category", researcher_category %>
    </p>
  <% end %>
</div>

<%= link_to "New researcher category", new_researcher_category_path %>

app/views/researcher_categories/new.html.erb
<h1>New researcher category</h1>

<%= render "form", researcher_category: @researcher_category %>

<br>

<div>
  <%= link_to "Back to researcher categories", researcher_categories_path %>
</div>

app/views/researcher_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @researcher_category %>

<div>
  <%= link_to "Edit this researcher category", edit_researcher_category_path(@researcher_category) %> |
  <%= link_to "Back to researcher categories", researcher_categories_path %>

  <%= button_to "Destroy this researcher category", @researcher_category, method: :delete %>
</div>