config/routes.rb
Rails.application.routes.draw do
  resources :payrolls
  resources :authorizations
  resources :requests
  resources :research_groups
  resources :contracts
  resources :user_experiences
  resources :patents
  resources :profiles
  resources :degrees
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :degree_types
  resources :vacants
  resources :research_types
  resources :fees
  resources :researcher_categories
  resources :experiences
  resources :contracted_teaching_categories
  resources :aspiring_teaching_categories
  resources :patent_types
  resources :areas
  resources :resources
  resources :actions
  resources :permissions
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "main#home"
end

app/models/aspiring_teaching_category.rb
# == Schema Information
#
# Table name: aspiring_teaching_categories
#
#  id          :integer          not null, primary key
#  descripcion :string
#  puntaje     :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class AspiringTeachingCategory < ApplicationRecord
    has_many :users
end

app/controllers/aspiring_teaching_categories_controller.rb
class AspiringTeachingCategoriesController < ApplicationController
  before_action :set_aspiring_teaching_category, only: %i[ show edit update destroy ]

  # GET /aspiring_teaching_categories or /aspiring_teaching_categories.json
  def index
    @aspiring_teaching_categories = AspiringTeachingCategory.all
  end

  # GET /aspiring_teaching_categories/1 or /aspiring_teaching_categories/1.json
  def show
  end

  # GET /aspiring_teaching_categories/new
  def new
    @aspiring_teaching_category = AspiringTeachingCategory.new
  end

  # GET /aspiring_teaching_categories/1/edit
  def edit
  end

  # POST /aspiring_teaching_categories or /aspiring_teaching_categories.json
  def create
    @aspiring_teaching_category = AspiringTeachingCategory.new(aspiring_teaching_category_params)

    respond_to do |format|
      if @aspiring_teaching_category.save
        format.html { redirect_to aspiring_teaching_category_url(@aspiring_teaching_category), notice: "Aspiring teaching category was successfully created." }
        format.json { render :show, status: :created, location: @aspiring_teaching_category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aspiring_teaching_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aspiring_teaching_categories/1 or /aspiring_teaching_categories/1.json
  def update
    respond_to do |format|
      if @aspiring_teaching_category.update(aspiring_teaching_category_params)
        format.html { redirect_to aspiring_teaching_category_url(@aspiring_teaching_category), notice: "Aspiring teaching category was successfully updated." }
        format.json { render :show, status: :ok, location: @aspiring_teaching_category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aspiring_teaching_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aspiring_teaching_categories/1 or /aspiring_teaching_categories/1.json
  def destroy
    @aspiring_teaching_category.destroy

    respond_to do |format|
      format.html { redirect_to aspiring_teaching_categories_url, notice: "Aspiring teaching category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aspiring_teaching_category
      @aspiring_teaching_category = AspiringTeachingCategory.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aspiring_teaching_category_params
      params.require(:aspiring_teaching_category).permit(:descripcion, :puntaje)
    end
end

app/helpers/aspiring_teaching_categories_helper.rb
module AspiringTeachingCategoriesHelper
end

app/views/aspiring_teaching_categories/_aspiring_teaching_category.html.erb
<div id="<%= dom_id aspiring_teaching_category %>">
  <p>
    <strong>Descripcion:</strong>
    <%= aspiring_teaching_category.descripcion %>
  </p>

  <p>
    <strong>Puntaje:</strong>
    <%= aspiring_teaching_category.puntaje %>
  </p>

</div>

app/views/aspiring_teaching_categories/_form.html.erb
<%= form_with(model: aspiring_teaching_category) do |form| %>
  <% if aspiring_teaching_category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aspiring_teaching_category.errors.count, "error") %> prohibited this aspiring_teaching_category from being saved:</h2>

      <ul>
        <% aspiring_teaching_category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_field :descripcion %>
  </div>

  <div>
    <%= form.label :puntaje, style: "display: block" %>
    <%= form.number_field :puntaje %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/aspiring_teaching_categories/edit.html.erb
<h1>Editing aspiring teaching category</h1>

<%= render "form", aspiring_teaching_category: @aspiring_teaching_category %>

<br>

<div>
  <%= link_to "Show this aspiring teaching category", @aspiring_teaching_category %> |
  <%= link_to "Back to aspiring teaching categories", aspiring_teaching_categories_path %>
</div>

app/views/aspiring_teaching_categories/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Aspiring teaching categories</h1>

<div id="aspiring_teaching_categories">
  <% @aspiring_teaching_categories.each do |aspiring_teaching_category| %>
    <%= render aspiring_teaching_category %>
    <p>
      <%= link_to "Show this aspiring teaching category", aspiring_teaching_category %>
    </p>
  <% end %>
</div>

<%= link_to "New aspiring teaching category", new_aspiring_teaching_category_path %>

app/views/aspiring_teaching_categories/new.html.erb
<h1>New aspiring teaching category</h1>

<%= render "form", aspiring_teaching_category: @aspiring_teaching_category %>

<br>

<div>
  <%= link_to "Back to aspiring teaching categories", aspiring_teaching_categories_path %>
</div>

app/views/aspiring_teaching_categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aspiring_teaching_category %>

<div>
  <%= link_to "Edit this aspiring teaching category", edit_aspiring_teaching_category_path(@aspiring_teaching_category) %> |
  <%= link_to "Back to aspiring teaching categories", aspiring_teaching_categories_path %>

  <%= button_to "Destroy this aspiring teaching category", @aspiring_teaching_category, method: :delete %>
</div>