config/routes.rb
Rails.application.routes.draw do
  resources :payrolls
  resources :authorizations
  resources :requests
  resources :research_groups
  resources :contracts
  resources :user_experiences
  resources :patents
  resources :profiles
  resources :degrees
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :degree_types
  resources :vacants
  resources :research_types
  resources :fees
  resources :researcher_categories
  resources :experiences
  resources :contracted_teaching_categories
  resources :aspiring_teaching_categories
  resources :patent_types
  resources :areas
  resources :resources
  resources :actions
  resources :permissions
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "main#home"
end

app/views/resources/_form.html.erb
<%= form_with(model: resource) do |form| %>
  <% if resource.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
        <% resource.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :descripcion, style: "display: block" %>
    <%= form.text_area :descripcion %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div id="<%= dom_id resource %>">
  <p>
    <strong>Nombre:</strong>
    <%= resource.nombre %>
  </p>

  <p>
    <strong>Descripcion:</strong>
    <%= resource.descripcion %>
  </p>

</div>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render "form", resource: @resource %>

<br>

<div>
  <%= link_to "Show this resource", @resource %> |
  <%= link_to "Back to resources", resources_path %>
</div>

app/views/resources/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Resources</h1>

<div id="resources">
  <% @resources.each do |resource| %>
    <%= render resource %>
    <p>
      <%= link_to "Show this resource", resource %>
    </p>
  <% end %>
</div>

<%= link_to "New resource", new_resource_path %>

app/views/resources/new.html.erb
<h1>New resource</h1>

<%= render "form", resource: @resource %>

<br>

<div>
  <%= link_to "Back to resources", resources_path %>
</div>

app/views/resources/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @resource %>

<div>
  <%= link_to "Edit this resource", edit_resource_path(@resource) %> |
  <%= link_to "Back to resources", resources_path %>

  <%= button_to "Destroy this resource", @resource, method: :delete %>
</div>