config/routes.rb
Rails.application.routes.draw do
  resources :payrolls
  resources :authorizations
  resources :requests
  resources :research_groups
  resources :contracts
  resources :user_experiences
  resources :patents
  resources :profiles
  resources :degrees
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  resources :degree_types
  resources :vacants
  resources :research_types
  resources :fees
  resources :researcher_categories
  resources :experiences
  resources :contracted_teaching_categories
  resources :aspiring_teaching_categories
  resources :patent_types
  resources :areas
  resources :resources
  resources :actions
  resources :permissions
  resources :roles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "main#home"
end

app/models/authorization.rb
# == Schema Information
#
# Table name: authorizations
#
#  id          :integer          not null, primary key
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  action_id   :integer          not null
#  resource_id :integer          not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_authorizations_on_action_id    (action_id)
#  index_authorizations_on_resource_id  (resource_id)
#  index_authorizations_on_user_id      (user_id)
#
# Foreign Keys
#
#  action_id    (action_id => actions.id)
#  resource_id  (resource_id => resources.id)
#  user_id      (user_id => users.id)
#
class Authorization < ApplicationRecord
  belongs_to :user
  belongs_to :resource
  belongs_to :action
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController
  before_action :set_authorization, only: %i[ show edit update destroy ]

  # GET /authorizations or /authorizations.json
  def index
    @authorizations = Authorization.all
  end

  # GET /authorizations/1 or /authorizations/1.json
  def show
  end

  # GET /authorizations/new
  def new
    @authorization = Authorization.new
  end

  # GET /authorizations/1/edit
  def edit
  end

  # POST /authorizations or /authorizations.json
  def create
    @authorization = Authorization.new(authorization_params)

    respond_to do |format|
      if @authorization.save
        format.html { redirect_to authorization_url(@authorization), notice: "Authorization was successfully created." }
        format.json { render :show, status: :created, location: @authorization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorizations/1 or /authorizations/1.json
  def update
    respond_to do |format|
      if @authorization.update(authorization_params)
        format.html { redirect_to authorization_url(@authorization), notice: "Authorization was successfully updated." }
        format.json { render :show, status: :ok, location: @authorization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @authorization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorizations/1 or /authorizations/1.json
  def destroy
    @authorization.destroy

    respond_to do |format|
      format.html { redirect_to authorizations_url, notice: "Authorization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authorization
      @authorization = Authorization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def authorization_params
      params.require(:authorization).permit(:user_id, :resource_id, :action_id)
    end
end

app/helpers/authorizations_helper.rb
module AuthorizationsHelper
end

app/views/authorizations/_authorization.html.erb
<div id="<%= dom_id authorization %>">
  <p>
    <strong>User:</strong>
    <%= authorization.user_id %>
  </p>

  <p>
    <strong>Resource:</strong>
    <%= authorization.resource_id %>
  </p>

  <p>
    <strong>Action:</strong>
    <%= authorization.action_id %>
  </p>

</div>

app/views/authorizations/_form.html.erb
<%= form_with(model: authorization) do |form| %>
  <% if authorization.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(authorization.errors.count, "error") %> prohibited this authorization from being saved:</h2>

      <ul>
        <% authorization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :resource_id, style: "display: block" %>
    <%= form.text_field :resource_id %>
  </div>

  <div>
    <%= form.label :action_id, style: "display: block" %>
    <%= form.text_field :action_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/authorizations/edit.html.erb
<h1>Editing authorization</h1>

<%= render "form", authorization: @authorization %>

<br>

<div>
  <%= link_to "Show this authorization", @authorization %> |
  <%= link_to "Back to authorizations", authorizations_path %>
</div>

app/views/authorizations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Authorizations</h1>

<div id="authorizations">
  <% @authorizations.each do |authorization| %>
    <%= render authorization %>
    <p>
      <%= link_to "Show this authorization", authorization %>
    </p>
  <% end %>
</div>

<%= link_to "New authorization", new_authorization_path %>

app/views/authorizations/new.html.erb
<h1>New authorization</h1>

<%= render "form", authorization: @authorization %>

<br>

<div>
  <%= link_to "Back to authorizations", authorizations_path %>
</div>

app/views/authorizations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @authorization %>

<div>
  <%= link_to "Edit this authorization", edit_authorization_path(@authorization) %> |
  <%= link_to "Back to authorizations", authorizations_path %>

  <%= button_to "Destroy this authorization", @authorization, method: :delete %>
</div>